
source 'git@github.com:HJ2018/HYNBase.git'
source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

target 'HYNDEMO_Example' do

 pod 'HYNDEMO', :path => '../'


  target 'HYNDEMO_Tests' do
    inherit! :search_paths

    
  end
end
